- name: Hello World AWX Sample
  hosts: all
  become: yes
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Ping
      ping:
    - name: Get external IP
      ipify_facts:
      register: ip
    - name: Get hostname
      shell: hostname
      register: hostname
    - name: Get user
      shell: whoami
      register: user
    - name: Print host, user and external IP
      debug:
        msg: "{{ user.stdout }} at {{ hostname.stdout }} ({{ ip.ansible_facts.ipify_public_ip }})"
    - name: Remove temp package if exists
      file:
        path: /tmp/htop.deb
        state: absent
      ignore_errors: yes
    - name: Download deb from url
      get_url:
        url: "http://ftp.br.debian.org/debian/pool/main/h/htop/htop_2.2.0-1+b1_amd64.deb"
        dest: /tmp/htop.deb
    - name: Install downloaded deb
      apt:
        deb: /tmp/htop.deb
        state: present
    - name: Install git
      apt:
        name: git
        state: latest
    - name: Check if HTOP is installed
      package_facts:
        manager: "auto"
    - name: HTOP test result
      debug: 
        msg: HTOP found
      when: "'htop' in ansible_facts.packages"
    - name: HTOP test result
      debug: 
        msg: HTOP NOT found
      when: "'htop' not in ansible_facts.packages"
    - name: Install NGINX
      apt:
        name: nginx
        state: latest
